---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "waiting"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: scope
    allow:
      - dependency-type: "production"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "waiting"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: scope
    allow:
      - dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "waiting"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      all-actions:
        patterns:
          - "*"
