---
version: 2
updates:
  - package-ecosystem: "pip"
    <<: &common
      directory: "/"
      schedule:
        interval: "weekly"
        day: "monday"
      cooldown:
        default-days: 7
      open-pull-requests-limit: 5
      labels:
        - "waiting"
        - "dependencies"
      commit-message:
        prefix: "chore"
        include: scope
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    <<: *common
    groups:
      all-actions:
        patterns:
          - "*"
