codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  range: 70..100
  status:
    changes: false
    project:
      default:
        target: 73.0
        threshold: 0
      fully_covered:
        target: 100.0
        paths:
          - errors.py
          - utils.py
    patch:
      default:
        target: 100.0
        branches: null
