---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6
        with:
          python-version-file: "pyproject.toml"
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7
      - name: Install gitlint
        run: uv tool install gitlint-core
      - name: Check commit messages
        run: gitlint --commits origin/${{ github.base_ref }}..HEAD

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6
        with:
          python-version-file: "pyproject.toml"
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7
        with:
          enable-cache: true
      - name: Setup enviroment
        run: uv sync
      - name: Run tests + cov report
        run: uv run make ISOLATE=0 test-with-coverage
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6
        with:
          python-version-file: "pyproject.toml"
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7
        with:
          enable-cache: true
      - name: Setup enviroment
        run: uv sync
      - name: Run Integration Tests
        run: |
          curl --retry 3 -sS -o /usr/local/bin/retry https://raw.githubusercontent.com/okurz/retry/refs/heads/main/retry
          chmod +x /usr/local/bin/retry
          uv run make ISOLATE=0 test-integration
